import ApiService from './api'
import AnalyticsService from './analyticsService'

class InsightsDownloadService {
  constructor() {
    this.analyticsService = new AnalyticsService(ApiService)
  }

  async generateUserInsightsReport() {
    try {
      const [
        recurringPayments,
        insights,
        analyticsData
      ] = await Promise.all([
        ApiService.getRecurringPayments().catch(() => []),
        ApiService.getLatestInsights().catch(() => null),
        this.analyticsService.getCategoryAnalytics().catch(() => ({ expenses: [], earnings: [] }))
      ])

      return this._compileReport({
        recurringPayments,
        insights,
        analyticsData
      })
    } catch (error) {
      console.error('Error generating report:', error)
      return this._getEmptyReport()
    }
  }

  _compileReport(data) {
    const reportDate = new Date().toLocaleDateString()
    const { recurringPayments, insights, analyticsData } = data

    return {
      reportDate,
      recurringPayments: recurringPayments.map(payment => ({
        name: payment.name || payment.merchant,
        amount: payment.amount,
        frequency: payment.frequency || 'Monthly',
        nextPayment: payment.nextPaymentDate || payment.dueDate
      })),
      analyticsData,
      aiInsights: insights?.insight?.aiText ? JSON.parse(insights.insight.aiText) : null
    }
  }

  _getEmptyReport() {
    return {
      reportDate: new Date().toLocaleDateString(),
      recurringPayments: [],
      analyticsData: { expenses: [], earnings: [] },
      aiInsights: null
    }
  }



  downloadReport(reportData) {
    const content = this._formatReportAsText(reportData)
    const blob = new Blob([content], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    
    const link = document.createElement('a')
    link.href = url
    link.download = `LifeLedger_Insights_${new Date().toISOString().split('T')[0]}.txt`
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)
    URL.revokeObjectURL(url)
  }

  _formatReportAsText(data) {
    return `
LIFELEDGER FINANCIAL REPORT
Generated on: ${data.reportDate}
============================

CHART ANALYTICS
---------------
Expenses by Category:
${data.analyticsData.expenses.map(exp => 
  `• ${exp.name}: ₹${exp.amount.toLocaleString()}`
).join('\n') || 'No expense data available'}

Earnings by Category:
${data.analyticsData.earnings.map(earn => 
  `• ${earn.name}: ₹${earn.amount.toLocaleString()}`
).join('\n') || 'No earnings data available'}

RECURRING PAYMENTS
------------------
${data.recurringPayments.length > 0 ? 
  data.recurringPayments.map(payment => 
    `• ${payment.name}: ₹${payment.amount.toLocaleString()} (${payment.frequency}) - Next: ${new Date(payment.nextPayment).toLocaleDateString()}`
  ).join('\n') : 'No recurring payments set up'}

${data.aiInsights ? `AI INSIGHTS
-----------
${JSON.stringify(data.aiInsights, null, 2)}
` : 'AI INSIGHTS\n-----------\nNo AI insights available\n'}
Report generated by LifeLedger
    `.trim()
  }
}

export default new InsightsDownloadService()